// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

//dev
// const awsmobile =  {
//     "aws_project_region": "us-east-1",
//     "aws_cognito_identity_pool_id": "us-east-1:3d734dbf-e7b7-4e42-978e-006d348924df",
//     "aws_cognito_region": "us-east-1",
//     "aws_mobile_analytics_app_id": "627755962b27479e9a8f5758dc2aab34",
//     "aws_mobile_analytics_app_region": "us-east-1"
// };



// prod

 const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8257c2cc-c4dd-4f20-9ec3-a55441cd5cfa",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "d4d3937c27a14a44b98032c1df9866f4",
    "aws_mobile_analytics_app_region": "us-east-1" 
 };


export default awsmobile;
